//! WGVB — deterministic, effectively unbounded procedural hex-world generator.
//!
//! The central invariant of this crate is:
//!
//! ```text
//! Tile = F(seed, coordinate, algorithm version, configuration)
//! ```
//!
//! with no dependency on generation order, thread scheduling, cache contents,
//! explored area, or persisted mutable state. Read `DESIGN.md` before changing
//! generator behavior or public APIs.
//!
//! This crate is intentionally free of persistence and rendering dependencies.

mod config;
mod coord;
mod elevation;
mod field;
mod generator;
mod hash;
mod noise;
mod region;
mod relief;
mod tile;

pub use config::{Config, ConfigError, MAX_CONTRAST_PASSES, MAX_FBM_OCTAVES};
pub use coord::{Coord, DIRECTION_COUNT, DIRECTIONS, Vec2, axial_to_world, direction_index};
pub use field::Field;
pub use generator::{Generator, Sample};
pub use hash::{
    DOM_BASIN, DOM_CONTINENTALNESS, DOM_DETAIL_WARP_X, DOM_DETAIL_WARP_Y, DOM_MOISTURE,
    DOM_REGION_STYLE, DOM_REGIONAL_ELEVATION, DOM_RELIEF, DOM_RIDGE_ORIENTATION,
    DOM_RIDGE_STRUCTURE, DOM_TEMPERATURE, DOM_TERRAIN_DETAIL, DOM_VOLCANIC, DOM_WARP_X, DOM_WARP_Y,
    domain, hash_n, hash2, hash3, signed_unit_f64, unit_f64,
};
pub use region::{RegionParams, UnitVec2};
pub use tile::{Climate, Elevation, HeatBand, MoistureBand, Terrain, Tile};

/// Generator algorithm version.
///
/// Changing any hash domain, field composition, threshold, default, the
/// coordinate-to-world conversion, or any classification rule changes existing
/// worlds and requires bumping this value. See `DESIGN.md` section 27.
///
/// # History
///
/// - **1** — phase 2 and phase 3. Four continuous scalar fields and the
///   hierarchical region blend.
/// - **2** — phase 4. Elevation. The composite gained a region uplift term, a
///   ridge structure term, a constant offset, and the contrast shaping; the
///   hill and detail weights were retuned down, which moved the four-field
///   composite that version 1 had already fixed. That last part is what makes
///   this a version bump rather than an addition: phase 3 could add region
///   influence without one because it left every existing value alone, and this
///   change does not.
pub const ALGORITHM_VERSION: u32 = 2;

/// World seed. One seed plus one [`Config`] plus one [`ALGORITHM_VERSION`]
/// determines every tile.
pub type Seed = u64;

/// Axial coordinate component type for the alpha world.
///
/// The world radius is derived from this choice. Widening it to `i32` changes
/// world topology and therefore requires a new [`ALGORITHM_VERSION`], even
/// though no schema migration is needed. See `DESIGN.md` section 4.
pub type Component = i16;

/// Radius of the canonical wrapped hexagonal map, in tiles.
///
/// The canonical domain is `-N <= q, r, s <= +N` with `q + r + s == 0`,
/// containing `1 + 3*N*(N+1)` tiles. See `DESIGN.md` section 7.1.
pub const WORLD_RADIUS: i64 = Component::MAX as i64;

/// Count of canonical tiles in the wrapped map, `1 + 3*N*(N+1)`.
///
/// This is also the index of the wraparound lattice generated by the six mirror
/// centers, which is why the canonical hexagon is an exact fundamental domain:
/// every coordinate has exactly one canonical representative.
pub const WORLD_TILE_COUNT: i64 = 1 + 3 * WORLD_RADIUS * (WORLD_RADIUS + 1);

/// Apothem of one hex, in miles. Adjacent hex centers are `2 * APOTHEM_MILES`
/// apart. See `DESIGN.md` section 7.
pub const APOTHEM_MILES: f64 = 3.0;

/// `sqrt(3.0)`, written out because it is needed in `const` context.
///
/// This is the exact `f64` nearest to the real square root of three, which is
/// bit-identical to `3.0_f64.sqrt()` on every IEEE-754 target. A unit test
/// asserts that equality rather than trusting the transcription.
pub(crate) const SQRT_3: f64 = 1.732_050_807_568_877_2;

/// Default chunk edge, in hexes. See `DESIGN.md` section 23.
///
/// Chunks are a caller and cache convenience; they do not define geography.
/// The effective value lives in [`Config`] so a world file records it.
pub const DEFAULT_CHUNK_SIZE_HEXES: u32 = 32;

/// Default region edge, in hexes. See `DESIGN.md` section 11.
pub const DEFAULT_REGION_SIZE_HEXES: u32 = 128;

/// Default macro-region edge, in hexes. See `DESIGN.md` section 11.
pub const DEFAULT_MACRO_REGION_SIZE_HEXES: u32 = 512;

// Type-level assertions. `DESIGN.md` sections 22 and 30.12: a future field with
// interior mutability must break the build here rather than be caught in
// review.
const _: () = {
    const fn assert_send_sync<T: Send + Sync>() {}
    assert_send_sync::<Generator>();
    assert_send_sync::<Config>();
    assert_send_sync::<Tile>();
    assert_send_sync::<RegionParams>();
    assert_send_sync::<Coord>();
};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sqrt_3_constant_matches_the_computed_square_root() {
        assert_eq!(SQRT_3, 3.0_f64.sqrt());
    }

    #[test]
    fn world_radius_is_derived_from_the_component_type() {
        assert_eq!(WORLD_RADIUS, 32_767);
    }

    #[test]
    fn world_tile_count_matches_the_documented_world_size() {
        // DESIGN.md section 7.2, derived independently: 1 + 3*N*(N+1) with
        // N = 32767 is 1 + 3 * 32767 * 32768.
        assert_eq!(WORLD_TILE_COUNT, 1 + 3 * 32_767 * 32_768);
        assert_eq!(WORLD_TILE_COUNT, 3_221_127_169);
    }

    #[test]
    fn tile_is_small_enough_for_allocation_free_batch_fills() {
        // DESIGN.md section 4.1 promises `Tile` stays under 64 bytes so batch
        // APIs can fill a `&mut [Tile]`.
        assert!(
            size_of::<Tile>() <= 64,
            "Tile is {} bytes",
            size_of::<Tile>()
        );
    }
}
