//! Wrapped-edge behavior of the continuous fields, and the world-warp seam.
//!
//! `DESIGN.md` sections 7.1 and 30.10. Two different properties live here and
//! are easy to confuse:
//!
//! 1. **Wrap consistency is exact.** A coordinate outside the canonical domain
//!    names the same tile as its canonical representative, so it must sample
//!    bit-identically. Tile identity, persistence keys, and region lookup all
//!    depend on this, and it holds structurally: [`Coord`] cannot be
//!    constructed non-canonically, so there is only one coordinate to sample.
//!
//! 2. **Wrap continuity is not exact, and is an accepted seam.** Two tiles that
//!    neighbor each other *across* a wrapped edge are roughly `393,204` miles
//!    apart in canonical world space, so their field values are uncorrelated and
//!    the join is visible. Section 7.1 permits this for the first
//!    implementation: WGVB makes a best effort at periodicity under the mirror
//!    translations, and where that is not achievable without disproportionate
//!    complexity, the discontinuity is a documented world-warp seam.
//!
//! Relief is not measured here and cannot be: a tile on an edge has a neighbor
//! across the wrap, so its relief saturates by construction. That is a
//! consequence of the seam rather than a second seam, and `tests/golden.rs`
//! pins the saturated values it produces.
//!
//! # Why the fields are not periodic yet
//!
//! A field is periodic under the mirror translations only if its noise lattice
//! is. The wraparound lattice is generated by mirror centers whose axial form is
//! `(2N+1, -N)` and `(N+1, -(2N+1))` with `N = 32767`, so `2N+1 = 65535` is the
//! period along `q`. Making a noise lattice close on that period requires every
//! wavelength in [`Config`] to divide `65535 = 3 * 5 * 17 * 257` in hexes, which
//! constrains the wavelengths to a sparse set — `65535 / 51 = 1285` hexes,
//! `65535 / 255 = 257` hexes, and so on — and constrains them jointly with the
//! fbm lacunarity, since every octave has to close as well.
//!
//! That is a real design decision with real costs to the multi-scale table of
//! section 10, and it is an algorithm compatibility change whenever it is taken.
//! Until then the seam is measured here rather than discovered later. **If a
//! future change makes the fields periodic, `the_wrapped_edges_are_a_documented_seam`
//! fails; that is deliberate — update it, update section 7.1, and bump
//! `ALGORITHM_VERSION`.**

use wgvb::{Coord, Generator, Sample, WORLD_RADIUS};

const SEED: u64 = 0x7777_1111_2222_3333;

/// Every scalar a [`Sample`] carries, named, in a fixed order.
fn scalars(s: &Sample) -> [(&'static str, f64); 11] {
    [
        ("continentalness", s.continentalness),
        ("regional", s.regional),
        ("local", s.local),
        ("detail", s.detail),
        ("ridge", s.ridge),
        ("elevation_raw", s.elevation_raw),
        ("regional_uplift", s.regional_uplift),
        ("roughness", s.roughness),
        ("elevation", s.elevation),
        ("heat", s.heat),
        ("moisture", s.moisture),
    ]
}

/// The six mirror centers in axial form, the rotations of `(2N+1, -N, -N-1)`.
///
/// Written out here rather than imported: the core crate keeps them private, and
/// a test that re-derives them from the published construction is a check on the
/// implementation rather than a restatement of it.
fn mirror_centers() -> [(i64, i64); 6] {
    let n = WORLD_RADIUS;
    let mut cube = (2 * n + 1, -n, -n - 1);
    let mut out = [(0_i64, 0_i64); 6];
    for slot in &mut out {
        *slot = (cube.0, cube.1);
        // One step in index order: (x, y, z) -> (-z, -x, -y).
        cube = (-cube.2, -cube.0, -cube.1);
    }
    out
}

#[test]
fn the_mirror_centers_close_and_sum_to_zero() {
    let n = WORLD_RADIUS;
    let centers = mirror_centers();
    for (q, r) in centers {
        let s = -q - r;
        assert_eq!(q + r + s, 0);
        // Each center is a rotation of the same vector, so the multiset of
        // absolute components is the same for all six.
        let mut components = [q.abs(), r.abs(), s.abs()];
        components.sort_unstable();
        assert_eq!(components, [n, n + 1, 2 * n + 1]);
    }
    // Six distinct directions.
    let mut unique = centers.to_vec();
    unique.sort_unstable();
    unique.dedup();
    assert_eq!(unique.len(), 6);
}

#[test]
fn sampling_across_every_wrapped_edge_is_bit_exact() {
    // Property 1. Six edges, each exercised from several starting points, and
    // from both sides: translating by a mirror center and by its negation must
    // both land back on the same sample.
    let generator = Generator::with_defaults(SEED);
    let n = WORLD_RADIUS;
    let starts = [
        (0_i64, 0_i64),
        (7, -3),
        (-411, 96),
        (n, -n),
        (-n, n),
        (n - 1, 0),
        (0, n - 1),
        (-n + 1, 0),
    ];

    for (q, r) in starts {
        let canonical = Coord::new(q, r);
        let expected = generator.sample(canonical);
        for (mq, mr) in mirror_centers() {
            for sign in [1_i64, -1] {
                let translated = Coord::new(q + sign * mq, r + sign * mr);
                assert_eq!(
                    translated, canonical,
                    "({q}, {r}) + {sign} * ({mq}, {mr}) left the canonical domain"
                );
                let actual = generator.sample(translated);
                for ((name, want), (_, got)) in scalars(&expected).into_iter().zip(scalars(&actual))
                {
                    assert_eq!(
                        want.to_bits(),
                        got.to_bits(),
                        "{name} differed across mirror ({mq}, {mr}) at ({q}, {r})"
                    );
                }
            }
        }
    }
}

#[test]
fn combinations_of_mirror_translations_also_sample_identically() {
    // The lattice is generated by the centers, so any integer combination of
    // them is also the identity on tiles. This is the case a single-step
    // normalizer would get right and a lattice solve could get wrong.
    let generator = Generator::with_defaults(SEED);
    let centers = mirror_centers();
    let canonical = Coord::new(123, -456);
    let expected = generator.sample(canonical);

    for (a, (aq, ar)) in centers.into_iter().enumerate() {
        for (b, (bq, br)) in centers.into_iter().enumerate() {
            for multiple in [1_i64, 2, 17, 1_000] {
                let translated = Coord::new(123 + multiple * aq + bq, -456 + multiple * ar + br);
                assert_eq!(translated, canonical, "centers {a} and {b}, x{multiple}");
                assert_eq!(generator.sample(translated), expected);
            }
        }
    }
}

/// The typical step between adjacent tiles in the field interior, for scale.
fn typical_interior_step(generator: &Generator) -> f64 {
    let mut sum = 0.0_f64;
    let mut count = 0_u32;
    for step in 0..400_i64 {
        let here = generator.sample(Coord::new(step, 17));
        let there = generator.sample(Coord::new(step + 1, 17));
        sum += (here.elevation_raw - there.elevation_raw).abs();
        count += 1;
    }
    sum / f64::from(count)
}

#[test]
fn the_wrapped_edges_are_a_documented_seam() {
    // Property 2. Walk off each of the six edges by one tile and measure the
    // step. This asserts the seam *exists*, which is not a wish: it is the
    // accepted state of section 7.1 for the first implementation, and pinning
    // it means a future change to periodicity has to be deliberate.
    let generator = Generator::with_defaults(SEED);
    let interior = typical_interior_step(&generator);
    assert!(interior > 0.0);

    let n = WORLD_RADIUS;
    // One coordinate on each of the six edges of the canonical hexagon, each
    // paired with the direction that steps off that edge.
    let edges: [((i64, i64), i32); 6] = [
        ((n, 0), 0),
        ((n, -n), 1),
        ((0, -n), 2),
        ((-n, 0), 3),
        ((-n, n), 4),
        ((0, n), 5),
    ];

    let mut seams = Vec::new();
    for ((q, r), direction) in edges {
        let edge = Coord::new(q, r);
        let across = edge.neighbor(direction);
        // Stepping off the edge must land somewhere else entirely — that is
        // what wrapping means — rather than on an adjacent tile.
        assert_ne!(across, edge);
        let step =
            (generator.sample(edge).elevation_raw - generator.sample(across).elevation_raw).abs();
        seams.push((q, r, direction, step));
    }

    let worst = seams
        .iter()
        .map(|(_, _, _, step)| *step)
        .fold(0.0_f64, f64::max);
    assert!(
        worst > interior * 10.0,
        "no wrapped edge shows a seam (worst {worst}, interior step {interior}); \
         if the fields are now periodic, update this test, DESIGN.md section 7.1, \
         and ALGORITHM_VERSION"
    );

    // The seam is a discontinuity, not a broken value: both sides are ordinary
    // normalized samples.
    for (q, r, direction, step) in seams {
        assert!(
            step <= 2.0,
            "seam at ({q}, {r}) direction {direction} is {step}, outside the field range"
        );
    }
}

#[test]
fn the_seam_is_the_only_discontinuity_near_an_edge() {
    // Walking *along* an edge, rather than off it, stays in the interior of
    // canonical world space, so it must be as smooth as anywhere else. A
    // normalizer that mis-handled coordinates near the boundary would show up
    // here even though every value it produced was canonical.
    let generator = Generator::with_defaults(SEED);
    let interior = typical_interior_step(&generator);
    let n = WORLD_RADIUS;

    for offset in 0..200_i64 {
        let here = Coord::new(n - offset, offset);
        let next = Coord::new(n - offset - 1, offset + 1);
        let step =
            (generator.sample(here).elevation_raw - generator.sample(next).elevation_raw).abs();
        assert!(
            step < interior * 20.0,
            "walking along the +q edge jumped {step} at offset {offset} \
             (typical interior step {interior})"
        );
    }
}
