//! Single-world SQLite persistence for WGVB.
//!
//! One database contains exactly one world and everything needed to reproduce
//! that world's generated baseline. See `DESIGN.md` section 27.
//!
//! ```text
//! generated terrain = algorithm version + seed + configuration + coordinates
//! ```
//!
//! Three of those four are singleton metadata here; the fourth is whatever the
//! caller asks for. What this crate stores beyond them is *authoritative player
//! state* — sparse overlays keyed by canonical `(q, r)`, and the frame each
//! player sees the world through, which is what gives their coordinates a
//! meaning at all. Generated tiles,
//! chunks, and rendered images are reproducible caches, not records, and none
//! of them is stored: section 27.6 says to measure before building a tile
//! cache, and `tests/bench.rs` in the core crate is that measurement.

mod overlay;
mod player;
mod schema;
mod world;

// The fingerprint moved to `wgvb-config` when `wgvb-tune` needed one without a
// database in its dependency graph. It is re-exported rather than merely moved,
// because a fingerprint is what this crate writes into a world file and
// `wgvb_store::fingerprint` is what every caller and every gate already names.
pub use overlay::{Bounds, Settlement};
pub use player::{Player, PlayerError};
pub use schema::SCHEMA_VERSION;
pub use wgvb_config::{
    CanonicalError, FINGERPRINT_LEN, Fingerprint, canonical_config_bytes, fingerprint,
    fingerprint_of_bytes,
};
pub use world::World;

/// `PRAGMA application_id` for every WGVB database: ASCII `"WGVB"`.
///
/// Reject a non-empty database carrying any other application id before
/// applying migrations or performing application writes. This differs from
/// WGVA's `0x5747_5641` by one byte, deliberately: a WGVA file must be rejected
/// by a WGVB binary at the first gate, and vice versa.
pub const APPLICATION_ID: i32 = 0x5747_5642;

/// Why opening a world failed.
///
/// One variant per gate of `DESIGN.md` section 27.5, so tests assert on
/// variants rather than on message strings. **No gate performs an application
/// write before it passes**, and a generator incompatibility is never handled
/// by silently regenerating the world with current rules — it is
/// [`OpenError::UnsupportedGeneratorVersion`] and nothing else.
#[derive(Debug, thiserror::Error)]
pub enum OpenError {
    /// Gate 1. The file is not a WGVB database — a WGVA file lands here.
    #[error("not a WGVB database: application_id is {found:#010x}, expected {expected:#010x}")]
    WrongApplicationId { found: i32, expected: i32 },
    /// Gate 2. The file was written by a newer binary.
    #[error("schema version {found} is newer than this binary supports ({supported})")]
    SchemaTooNew { found: u32, supported: u32 },
    /// Gate 5. The world was generated by rules this binary does not have.
    #[error("world was generated by algorithm version {0}, which this binary cannot reproduce")]
    UnsupportedGeneratorVersion(u32),
    /// Gate 4. The singleton row is missing, duplicated, or undecodable.
    ///
    /// Also covers a configuration that cannot be reduced to canonical bytes
    /// ([`CanonicalError`]): metadata that will not serialize is metadata that
    /// cannot be made sense of, which is what this variant means.
    #[error("world metadata is missing or malformed: {0}")]
    MalformedMetadata(String),
    /// Gate 4. The stored configuration bytes do not hash to the stored
    /// fingerprint, so one of the two has been edited.
    #[error("stored configuration does not match its fingerprint")]
    FingerprintMismatch,
    /// Gate 4. The stored configuration decodes but is not a configuration any
    /// binary should generate from.
    #[error(transparent)]
    Config(#[from] wgvb::ConfigError),
    /// The database itself refused.
    #[error(transparent)]
    Sqlite(#[from] rusqlite::Error),
}

impl From<CanonicalError> for OpenError {
    fn from(error: CanonicalError) -> OpenError {
        OpenError::MalformedMetadata(error.to_string())
    }
}

// A type-level assertion, on the same terms as the core crate's: section 27.7
// says a `World` is per-thread or behind a `Mutex`, and the way to keep the
// first half of that true is to have the compiler check it.
//
// Only the positive half is asserted. `World` is not `Sync`, because
// `rusqlite::Connection` is not, and there is no stable way to assert the
// absence of an auto trait that does not itself go stale the day the assertion
// would start mattering. What holds the rule up is that nothing here wraps the
// connection in anything that would add `Sync` back.
const _: () = {
    const fn assert_send<T: Send>() {}
    assert_send::<World>();

    // An empty ladder would make `SCHEMA_VERSION` zero, which is also what an
    // uninitialized database reports: every gate 2 comparison would pass and a
    // created database would carry no schema at all.
    assert!(SCHEMA_VERSION >= 1, "the migration ladder is empty");
};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_application_id_is_the_ascii_for_wgvb_and_not_wgva() {
        // Derived from the four letters rather than copied from the constant:
        // a transcription error here is a file format that rejects itself.
        let wgvb = i32::from_be_bytes(*b"WGVB");
        let wgva = i32::from_be_bytes(*b"WGVA");
        assert_eq!(APPLICATION_ID, wgvb);
        assert_ne!(APPLICATION_ID, wgva);
        assert_eq!(APPLICATION_ID, 1_464_292_930);
    }
}
